# Generated by Django 4.2.5 on 2023-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_no_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mentions',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
