# Generated by Django 4.2.5 on 2023-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0003_alter_reservation_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer_phone",
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
