# Generated by Django 4.2.5 on 2023-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0004_reservation_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.CharField(max_length=5),
        ),
    ]
